<a href="https://colab.research.google.com/github/Etor-git/ciencia_de_datos/blob/main/Creaci%C3%B3n%20y%20Manipulaci%C3%B3n%20B%C3%A1sica.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
# 1. Crear el generador aleatorio
rng = np.random.default_rng(seed=42)
# 2. Crear un arreglo 3x4
data = rng.standard_normal((3, 4))
print("Arreglo original:\n", data)
# 3. Multiplicar todos los elementos por 10 y convertir a enteros (int32)
data_int = (data * 10).astype(np.int32)
print("\nArreglo transformado (int32):\n", data_int)

Arreglo original:
 [[ 0.30471708 -1.03998411  0.7504512   0.94056472]
 [-1.95103519 -1.30217951  0.1278404  -0.31624259]
 [-0.01680116 -0.85304393  0.87939797  0.77779194]]

Arreglo transformado (int32):
 [[  3 -10   7   9]
 [-19 -13   1  -3]
 [  0  -8   8   7]]
