<a href="https://colab.research.google.com/github/Etor-git/ciencia_de_datos/blob/main/Creaci%C3%B3n%20con%20Tipos%20de%20Datos%20Espec%C3%ADficos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
# 1. Crear arreglo 3x3 de ceros int32
arr = np.zeros((3, 3), dtype=np.int32)
# 2. Cambiar la diagonal (usando indexing básico o np.eye como referencia)
np.fill_diagonal(arr, 1)
print("Arreglo con diagonal de unos:\n", arr)
print("Dtype:", arr.dtype) # Debe ser int32

Arreglo con diagonal de unos:
 [[1 0 0]
 [0 1 0]
 [0 0 1]]
Dtype: int32
