<a href="https://colab.research.google.com/github/Etor-git/ciencia_de_datos/blob/main/Ejercicios_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Ejercicios Prácticos en Python


NumPy (Numerical Python), el paquete fundamental para la computación científica en Python. Su
principal característica es el ndarray, un objeto de arreglo multidimensional rápido y flexible que
permite realizar operaciones matemáticas en bloques enteros de datos con una sintaxis similar a la de los
escalares.
1. El objeto ndarray
 Homogeneidad: A diferencia de las listas de Python, todos los elementos de un ndarray deben
ser del mismo tipo (dtype).
 Eficiencia: NumPy almacena los datos en bloques continuos de memoria, lo que permite que
algoritmos escritos en C operen sin la sobrecarga de Python, resultando en velocidades de 10 a
100 veces superiores.
 Creación: Se pueden crear arreglos usando np.array() (desde listas), o funciones como
np.zeros(), np.ones() y np.arange().
2. Operaciones y Vectorización
 Aritmética: Las operaciones entre arreglos del mismo tamaño se aplican elemento a elemento.
 Broadcasting: Es el proceso por el cual NumPy maneja operaciones entre arreglos de diferentes
tamaños.
 Ufuncs (Funciones Universales): Son funciones que realizan operaciones rápidas elemento a
elemento, como np.sqrt(), np.exp() (unarias) o np.add() y np.maximum()
(binarias).
3. Indexación y Segmentación (Slicing)
 Vistas vs. Copias: Una distinción crítica es que los cortes (slices) de arreglos son vistas del
arreglo original. Esto significa que cualquier modificación en el corte se reflejará en los datos
originales para ahorrar memoria.
 Indexación Booleana: Permite filtrar datos usando comparaciones vectorizadas (ej. data[names
== "Bob"]).
 Fancy Indexing: Se refiere a la indexación mediante arreglos de enteros para seleccionar
subconjuntos en un orden específico. A diferencia del slicing, esto siempre crea una copia.
4. Métodos Matemáticos y Estadísticos
NumPy ofrece métodos integrados para procesar estadísticas de todo el arreglo o a lo largo de un eje
(axis):
 Reducciones: sum(), mean(), std() (desviación estándar).
 Acumulaciones: cumsum() (suma acumulada).
 Lógica Condicional: np.where(condición, valor_si_true,
valor_si_false) es una versión vectorizada de la expresión ternaria de Python.

# Ejercicio 1: Creación y Manipulación Básica

In [1]:
import numpy as np

In [2]:
# 1. Crear el generador aleatorio
rng = np.random.default_rng(seed=42)
# 2. Crear un arreglo 3x4
data = rng.standard_normal((3, 4))
print("Arreglo original:\n", data)
# 3. Multiplicar todos los elementos por 10 y convertir a enteros (int32)
data_int = (data * 10).astype(np.int32)
print("\nArreglo transformado (int32):\n", data_int)

Arreglo original:
 [[ 0.30471708 -1.03998411  0.7504512   0.94056472]
 [-1.95103519 -1.30217951  0.1278404  -0.31624259]
 [-0.01680116 -0.85304393  0.87939797  0.77779194]]

Arreglo transformado (int32):
 [[  3 -10   7   9]
 [-19 -13   1  -3]
 [  0  -8   8   7]]


# Ejercicio 2: Indexación y Vistas (Slicing)
Instrucciones: Demuestra la diferencia entre una vista y una copia.

In [5]:
# 1. Crea un arreglo del 0 al 9
arr = np.arange(10)
# 2. Crea un slice de los elementos del índice 5 al 8 y cámbialos a 12
arr_slice = arr[5:8]
arr_slice = 12345
# 3. Observa el arreglo original
print("Arreglo original modificado por el slice:", arr)
# El índice 6 habrá cambiado
# 4. Ahora haz lo mismo pero usando .copy()
arr_copy = arr[5:8].copy()
arr_copy[:] = 0
print("Arreglo original tras modificar una copia:", arr) # No habrá cambiado

Arreglo original modificado por el slice: [0 1 2 3 4 5 6 7 8 9]
Arreglo original tras modificar una copia: [0 1 2 3 4 5 6 7 8 9]


# Ejercicio 3: Indexación Booleana y np.where
Instrucciones: Dado un arreglo de datos, sustituye todos los valores negativos por 0 y los positivos por 1.

In [6]:
rng = np.random.default_rng()
data = rng.standard_normal((4, 4))
print("Datos originales:\n", data)
# Usando np.where para lógica condicional
resultado = np.where(data > 0, 1, 0)
print("\nDatos binarizados (0 o 1):\n", resultado)
# Alternativa: Sustituir solo negativos por 0 en el arreglo original
data[data < 0] = 0
print("\nArreglo original filtrado (solo >= 0):\n", data)

Datos originales:
 [[-1.33431455  0.47397971  0.62128567 -1.27215204]
 [-0.07082828 -0.77673159  0.01461822 -0.9348807 ]
 [-0.46575497  0.28923575  1.98200612  1.47487358]
 [ 1.09489874  0.22366724  0.03130761  0.66741759]]

Datos binarizados (0 o 1):
 [[0 1 1 0]
 [0 0 1 0]
 [0 1 1 1]
 [1 1 1 1]]

Arreglo original filtrado (solo >= 0):
 [[0.         0.47397971 0.62128567 0.        ]
 [0.         0.         0.01461822 0.        ]
 [0.         0.28923575 1.98200612 1.47487358]
 [1.09489874 0.22366724 0.03130761 0.66741759]]


# Ejercicio 4: Estadísticas por Ejes
Instrucciones: Crea una matriz de 5x4 y calcula el promedio de cada columna y la suma total de cada
fila.

In [7]:
rng = np.random.default_rng()
arr = rng.standard_normal((5, 4))
# axis=0 son las columnas (hacia abajo a través de las filas)
print("Promedio por columna:", arr.mean(axis=0))
# axis=1 son las filas (a través de las columnas)
print("Suma por fila:", arr.sum(axis=1))

Promedio por columna: [-0.02387732 -0.43128086 -0.02206939 -0.15527814]
Suma por fila: [ 1.80436226 -1.65810948  0.9971844  -3.31538233 -0.99058342]


# Ejercicio 5: Álgebra Lineal Básica
Instrucciones: Realiza una multiplicación de matrices entre una matriz de 2x3 y su transpuesta.

In [8]:
rng = np.random.default_rng()
X = rng.standard_normal((2, 3))
# Multiplicación de matriz por su transpuesta usando el operador @
resultado = X @ X.T
print("Resultado de X multiplicado por X transpuesta:\n", resultado)
# Alternativa usando np.dot
resultado_dot = np.dot(X, X.T)

Resultado de X multiplicado por X transpuesta:
 [[ 2.11599997 -1.5162049 ]
 [-1.5162049  11.04157116]]


# 5 Ejercicios Prácticos Adicionales

## **Ejercicio 6: Creación con Tipos de Datos Específicos**

Instrucciones: Crea un arreglo de 3x3 lleno de ceros, pero asegúrate de que el tipo de dato sea entero de
32 bits (int32). Luego, cambia todos los elementos de la diagonal principal a 1.

In [11]:
import numpy as np
# 1. Crear arreglo 3x3 de ceros int32
arr = np.zeros((3, 3), dtype=np.int32)
# 2. Cambiar la diagonal (usando indexing básico o np.eye como referencia)
arr[np.diag_indices(3)] = 1
print("Arreglo con diagonal de unos:\n", arr)
print("Dtype:", arr.dtype) # Debe ser int32

Arreglo con diagonal de unos:
 [[1 0 0]
 [0 1 0]
 [0 0 1]]
Dtype: int32


# Ejercicio 7: Filtrado Lógico Complejo

Instrucciones: Crea un arreglo con los números del 1 al 20. Utiliza indexación booleana para seleccionar solo los números que sean mayores que 10 y que sean pares.

In [12]:
arr = np.arange(1, 21)
# Crear la máscara booleana combinando condiciones con &
mask = (arr > 10) & (arr % 2 == 0)
resultado = arr[mask]
print("Números > 10 y pares:", resultado)

Números > 10 y pares: [12 14 16 18 20]


# Ejercicio 8: Transformaciones y Transposición

Instrucciones: Crea un arreglo de 15 elementos (0 a 14) y cámbiale la forma (reshape) a una matriz de 3x5. Luego, obtén su transpuesta y explica qué sucede con la forma.

In [13]:
#Crear un elemento
arr = np.arange(15).reshape((3, 5))
print("Forma original:", arr.shape) # (3, 5)
# Obtener la transpuesta usando el atributo .T
arr_t = arr.T
print("Forma de la transpuesta:", arr_t.shape) # Debe ser (5, 3)

Forma original: (3, 5)
Forma de la transpuesta: (5, 3)


# Ejercicio 9: Uso de Funciones Universales (ufuncs) Binarias

Instrucciones: Crea dos arreglos de 5 números aleatorios cada uno. Utiliza la función np.maximum para obtener un tercer arreglo que contenga el valor más alto de cada posición comparada.

In [14]:
rng = np.random.default_rng(seed=123)
x = rng.standard_normal(5)
y = rng.standard_normal(5)
# np.maximum compara elemento a elemento
resultado = np.maximum(x, y)
print("X:", x)
print("Y:", y)
print("Máximos elemento a elemento:", resultado)

X: [-0.98912135 -0.36778665  1.28792526  0.19397442  0.9202309 ]
Y: [ 0.57710379 -0.63646365  0.54195222 -0.31659545 -0.32238912]
Máximos elemento a elemento: [ 0.57710379 -0.36778665  1.28792526  0.19397442  0.9202309 ]


# Ejercicio 10: Valores Únicos y Ordenamiento

Instrucciones: Dado el siguiente arreglo con valores duplicados: ``, utiliza NumPy para obtener un
arreglo con los valores únicos ordenados de menor a mayor.

In [15]:
datos = np.array([100, 12, 30, 4, 34])
# np.unique devuelve los valores únicos ya ordenados
unicos = np.unique(datos)
print("Valores únicos ordenados:", unicos)

Valores únicos ordenados: [  4  12  30  34 100]
