<a href="https://colab.research.google.com/github/Etor-git/ciencia_de_datos/blob/main/Indexaci%C3%B3n%20Booleana%20y%20np.where.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
rng = np.random.default_rng()
data = rng.standard_normal((4, 4))
print("Datos originales:\n", data)
# Usando np.where para lógica condicional
resultado = np.where(data > 0, 1, 0)
print("\nDatos binarizados (0 o 1):\n", resultado)
# Alternativa: Sustituir solo negativos por 0 en el arreglo original
data[data < 0] = 0
print("\nArreglo original filtrado (solo >= 0):\n", data)

Datos originales:
 [[-0.23798688 -0.27265933 -0.5462969   1.45470341]
 [ 0.9124615  -0.54055277 -0.25895119  1.15166389]
 [-0.13124023 -0.32066668  0.93168557  0.2315303 ]
 [ 1.21290527  0.20170058  1.34073834  2.26722206]]

Datos binarizados (0 o 1):
 [[0 0 0 1]
 [1 0 0 1]
 [0 0 1 1]
 [1 1 1 1]]

Arreglo original filtrado (solo >= 0):
 [[0.         0.         0.         1.45470341]
 [0.9124615  0.         0.         1.15166389]
 [0.         0.         0.93168557 0.2315303 ]
 [1.21290527 0.20170058 1.34073834 2.26722206]]
